AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Notification-Delivery-Service

  Sample SAM Template for Notification-Delivery-Service

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs12.x

Resources:

 NotificationDeliveryQueue:
    Type: AWS::SQS::Queue
    Properties:
      ContentBasedDeduplication: true
      DelaySeconds: 0
      FifoQueue: true
      KmsDataKeyReusePeriodSeconds: 86400 # 24 hours, for details
      # KmsMasterKeyId: String    # default will be used (aws managed)
      MaximumMessageSize: 10240 # 10 KB
      MessageRetentionPeriod: 60 # 1 minute
      QueueName: NotificationDeliveryQueue.fifo
      ReceiveMessageWaitTimeSeconds: 20 # 20 second (max), For long polling
      # RedrivePolicy:                    # to attach a dead-letter-queue, this is different DLQ than the one used for fail cases.
      #   deadLetterTargetArn: String
      #   maxReceiveCount: Integer
      # Tags:
      #   - Tag
      VisibilityTimeout: 30 # 30 seconds

  NotificationDeliveryLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: NotificationDeliveryLambdaFunction
      CodeUri: notification-delivery-queue-lambda/
      Handler: dist/app.lambdaHandler
      Runtime: nodejs12.x
      MemorySize: 256
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            BatchSize: 10
            Enabled: true
            Queue: # ARN of queue
              Fn::Join:
                - ""
                - - "arn:aws:sqs:"
                  - Ref: "AWS::Region"
                  - ":"
                  - Ref: "AWS::AccountId"
                  - ":NotificationDeliveryQueue.fifo"

      Policies:
        - AWSLambdaSQSQueueExecutionRole    # access permissions of SQS

        - DynamoDBCrudPolicy:
            TableName: GeneralPopTable
        





Outputs:
  NotificationDeliveryQueue:
    Description: "URL of new FIFO SQS Queue for notification delivery to users via a lambda function"
    Value:
      Ref: NotificationDeliveryQueue
  NotificationDeliveryQueueARN:
    Description: "ARN of new FIFO SQS Queue for notification delivery to users via a lambda function"
    Value:
      Fn::GetAtt:
        - NotificationDeliveryQueue
        - Arn

